#Auth2 Authorization end point
security:
    oauth2:
        client:
            access-token-uri: https://dev-210340.oktapreview.com/oauth2/gd/v1/token
            user-authorization-uri: https://dev-210340.oktapreview.com/oauth2/gd/v1/authorize
            client-id: 0oafjvvexw3hsmNo30h7
            scope: openid profile email
        resource:
            user-info-uri: https://dev-210340.oktapreview.com/oauth2/gd/v1/userinfo
            token-info-uri: https://dev-210340.oktapreview.com/oauth2/gd/v1/introspect
            prefer-token-info: false
server:
  port: 8090
  servlet:
    context-path: /spring-boot

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true



debug: false

#Swagger Configuration
springfox:
  documentation:
    swagger:
      v2:
        path: /restAPI